const GLYPH_FONT_FAMILY = 'Charter, "Bitstream Charter", "Sitka Text", Cambria, serif';
const GLYPH_CELL_PADDING_RATIO = 0.08;
const FIELD_MODIFIER_BRIGHTNESS_BOOST = 1;
const FIELD_MODIFIER_BRIGHTNESS_FLOOR = 0.07;
const FIELD_MODIFIER_BRIGHTNESS_WHITE_POINT = 1;
const FIELD_MODIFIER_SAMPLE_SIZE = 256;
const MAX_FIELD_MODIFIER_REGIONS = 8;
const NOISE_VISUAL_WHITE_POINT = 0.63;
const PROCEDURAL_LAYOUT_SAMPLE_RATE = 9;

const GLYPH_RASTER_SHADER_OPTIONS = {
  fieldModifierBrightnessBoost: FIELD_MODIFIER_BRIGHTNESS_BOOST,
  fieldModifierBrightnessFloor: FIELD_MODIFIER_BRIGHTNESS_FLOOR,
  fieldModifierBrightnessWhitePoint: FIELD_MODIFIER_BRIGHTNESS_WHITE_POINT,
  fieldModifierSampleSize: FIELD_MODIFIER_SAMPLE_SIZE,
  maxFieldModifierRegions: MAX_FIELD_MODIFIER_REGIONS,
  noiseVisualWhitePoint: NOISE_VISUAL_WHITE_POINT,
};

export {
  FIELD_MODIFIER_SAMPLE_SIZE,
  GLYPH_CELL_PADDING_RATIO,
  GLYPH_FONT_FAMILY,
  GLYPH_RASTER_SHADER_OPTIONS,
  MAX_FIELD_MODIFIER_REGIONS,
  PROCEDURAL_LAYOUT_SAMPLE_RATE,
};
